apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "mysql-user-mgmt.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "mysql-user-mgmt.name" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "mysql-user-mgmt.name" . }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "mysql-user-mgmt.name" . }}
    spec:
      serviceAccountName: {{ include "mysql-user-mgmt.serviceAccountName" . }}
      containers:
        - name: mysql-user-mgmt
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          {{- if .Values.externalSecrets.enabled }}
          envFrom:
            - secretRef:
                name: {{ include "mysql-user-mgmt.fullname" . }}-secrets
          {{- end }}
          livenessProbe:
            httpGet:
              path: {{ .Values.probes.liveness.path }}
              port: http
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: {{ .Values.probes.readiness.path }}
              port: http
            initialDelaySeconds: 5
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
