{{- if .Values.externalSecrets.enabled }}
apiVersion: kubernetes-client.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "mysql-user-mgmt.fullname" . }}-secrets
  labels:
    app.kubernetes.io/name: {{ include "mysql-user-mgmt.name" . }}
spec:
  backendType: systemManager
  data:
    {{- toYaml .Values.externalSecrets.secrets | nindent 4 }}
{{- end }}
