{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "mysql-user-mgmt.serviceAccountName" . }}
  labels:
    app.kubernetes.io/name: {{ include "mysql-user-mgmt.name" . }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
